version: "3"

networks:
  backend-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5008:80"
      - "5009:443"
    env_file:  
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks: 
      - backend-network
      
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes: 
  db-data: