@api_HostAddress = http://localhost:5008

GET {{api_HostAddress}}/health
Accept: application/json

###

POST {{api_HostAddress}}/auth
Accept: application/json
Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "email": "string",
  "password": "string"
}