@api_HostAddress = http://localhost:5008

GET {{api_HostAddress}}/health
Accept: application/json

### Auth

POST {{api_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

// The token comes back as 'value' in the response body
{
  "email": "string",
  "password": "string"
}

> {% client.global.set("auth_token", response.body.value) %}