@api_HostAddress = http://localhost:5008

GET {{api_HostAddress}}/health
Accept: application/json

### Auth

# Login and set token
POST {{api_HostAddress}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

> {%
    client.global.set("auth_token", response.body.value)
%}

### User